### ISSUE TITLE
Can you support `order` and `excludeKeyword` in `searchCondition`?

### ISSUE THREAD

**Issue by MitsuPa** [take-kun/mercapi#16]
-   `order`
  ![Snipaste_2023-11-13_18-59-38](https://github.com/take-kun/mercapi/assets/80208659/4ef0a734-8fe7-455b-8fd8-3efa3c56a018)
- `excludeKeyword`
  ![Snipaste_2023-11-13_18-59-24](https://github.com/take-kun/mercapi/assets/80208659/2c608e1c-f6d1-4f27-9a4d-39d6cd4e72c4)

Thank you for your efforts!

**Comment by take-kun** [comment]
Hi, sorry for getting so late to you. Actually I already have sorting order support prepared, but it still requires some testing.
